id: PF5628224
initial_creation_type: input
source_metadata:
  title: Shechen Gyaltsab Gyurme Pema Namgyal
  language: en
  description: 'Texts by and about Shechen Gyatsab Gyurme Pema Namgyal (zhe chen rgyal
    tshab ''gyur med padma rnam rgyal, 1871–1926):'
  volume:
    745712a06ab34e5c9baf1020a646c660:
      title: Advice for Gelong Jampa Dargye
      parent: Advice
    50bc6bcebeb144b4a28502b2685d163d:
      title: A Prayer of Aspiration
      parent: Aspiration Prayers
    c3eb933021f548e199eddaa57fac1cf2:
      title: Lamp Aspiration Prayer
      parent: Aspiration Prayers
    56d636fc2935408f8e1cbdfce872726f:
      title: Biography of Shechen Gyaltsab Gyurme Pema Namgyal
      parent: Biography
    025baf7cd1fb40d0b16c94cb4fb8d97c:
      title: Brief Offering Prayer to Gesar
      parent: Dharma Protectors
    7201f87e9258487bbf6e624d98155ec3:
      title: 'Pacifying the Turmoil of the Mamos: A Concise Liturgy'
      parent: Dharma Protectors
    5f0fe00a3f3e44eb9c8c59fc31afc767:
      title: Guru Yoga of the Great Omniscient One, Longchenpa
      parent: Guru Yoga
    41feeaa2e5ea4eb6b4442d7542727600:
      title: 'Swift Infusion of Blessings: A Guru Yoga based on Jamgön Mipham Gyatso'
      parent: Guru Yoga
    cdc1946a63e749099198ae8b019911bc:
      title: Prayer for the Long Life of Jamyang Khyentse Chökyi Lodrö
      parent: Long Life Prayers
    782c41d5a4be43f1a03a11aab2bca790:
      title: Prayer for the Long Life of Shechen Rabjam Rinpoche
      parent: Long Life Prayers
    fc9c68797f74408a800b53edc721de35:
      title: A Prayer To Padmasambhava
      parent: Prayers
    3602d8cc27774980b11791f833989a72:
      title: A Prayer to Amitāyus
      parent: Prayers
    6d0f9891eed64d1c8a0015c134314ef7:
      title: A Prayer to Mañjughoṣa
      parent: Prayers
    950a8249be3a499f9aeaad33bf9369d6:
      title: A Prayer to the Vajradhara of Oḍḍiyāna
      parent: Prayers
    cb2bedeafebe442d822e966a188b5c6a:
      title: A Concise Feast Prayer
      parent: Tsok
created_at: '2022-03-01T01:34:05.451007'
last_modified_at: '2022-03-01T01:34:05.451013'
